name: 'maven deploy'
description: 'deploy using maven as build tool'
inputs:
  java-version:
    description: 'jdk version'
    default: '17'
  java-distribution:
    description: 'jdk distribution'
    default: 'temurin'
  gpg-private-key:
    description: 'private key for artifact signing'
    default: ${{ secrets.ARTIFACT_SIGNING_GPG_PRIVATE_KEY }}
  gpg-key-name:
    description: 'name of the gpg private key'
    default: ${{ secrets.ARTIFACT_SIGNING_GPG_KEY_NAME }}
  gpg-passphrase:
    description: 'pass phrase for te gpg signing key'
    default: ${{ secrets.ARTIFACT_SIGNING_GPG_PRIVATE_KEY_PASSWORD }}
  deploy-user:
    description: "user to authenticate at artifact repository"
    default: ${{ secrets.DEPLOY_USER_GITHUB_PACKAGES }}
  deploy-password:
    description: "password to authenticate at artifact repository"
    default: ${{ secrets.DEPLOY_TOKEN_GITHUB_PACKAGES }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: set up jdk
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: maven
        gpg-private-key: ${{ inputs.gpg-private-key }}
        server-username: SERVER_USER
        server-password: SERVER_PASSWORD
    - name: execute maven
      shell: bash
      run: export GPG_TTY=$(tty) && mvn --batch-mode deploy -e
      env:
        GPG_KEY_NAME: ${{ inputs.gpg-key-name }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
        SERVER_USER: ${{ inputs.deploy-user }}
        SERVER_PASSWORD: ${{ inputs.deploy-password }}